DROP SCHEMA ACADEMIA;
CREATE SCHEMA ACADEMIA;

USE ACADEMIA;

CREATE TABLE ARM_ARMARIO (
  ARM_ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  ARM_FILEIRA VARCHAR(10) NOT NULL,
  ARM_COLUNA VARCHAR(10) NOT NULL,
  ARM_CORREDOR VARCHAR(10) NOT NULL,
  CONSTRAINT ARM_ARMARIO_PK PRIMARY KEY (ARM_ID)
);

CREATE TABLE PES_PESSOA (
  PES_ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  PES_NOME VARCHAR(10) NOT NULL,
  PES_DATA DATE NOT NULL,
  PES_SEXO VARCHAR(10) NOT NULL,
  CONSTRAINT PES_PESSOA_PK PRIMARY KEY (PES_ID)
);

CREATE TABLE PRF_PROFESSOR (
  PES_ID INTEGER UNSIGNED NOT NULL,
  FOREIGN KEY PRP_PROFESSORPESSOA_FK (PES_ID) REFERENCES PES_PESSOA (PES_ID) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE ATL_ATLETA (
  PES_ID INTEGER UNSIGNED NOT NULL,
  ARM_ID INTEGER UNSIGNED NOT NULL,
  FOREIGN KEY ATP_ATLETAPESSOA_FK (PES_ID) REFERENCES PES_PESSOA (PES_ID) ON DELETE RESTRICT ON UPDATE CASCADE,
  FOREIGN KEY ATA_ATLETAARMARIO_FK (ARM_ID) REFERENCES ARM_ARMARIO (ARM_ID) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE MOD_MODALIDADE (
  MOD_ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  MOD_NOME VARCHAR(40) NOT NULL,
  MOD_ATIVO BOOLEAN NOT NULL,
  MOD_DESCRICAO VARCHAR(50) NOT NULL,
  PES_ID INTEGER UNSIGNED NOT NULL,
  CONSTRAINT MOD_MODALIDADE_PK PRIMARY KEY (MOD_ID),
  FOREIGN KEY PRP_MODALIDADEPROFESSOR_FK (PES_ID) REFERENCES PRF_PROFESSOR (PES_ID) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE ATM_ATLETA_MODALIDADE (
  ATL_ID INTEGER UNSIGNED NOT NULL,
  MOD_ID INTEGER UNSIGNED NOT NULL,
  PRIMARY KEY (ATL_ID, MOD_ID),
  FOREIGN KEY ATM_ATLETA_FK (ATL_ID) REFERENCES PES_PESSOA (PES_ID) ON DELETE RESTRICT ON UPDATE CASCADE,
  FOREIGN KEY ATM_MODALIDADE_FK (MOD_ID) REFERENCES MOD_MODALIDADE (MOD_ID) ON DELETE RESTRICT ON UPDATE CASCADE
);